slab_shelves:
  enabled: true
chiseled_bookshelf_display:
  enabled: true
  view_radius: 3
auto_animal_feeding:
  enabled: false
  radius: 16
  cooldownms: 30000
  task:
    delay: 20
    period: 40
flags:
  enabled: true
  materials:
    - BLACK_WOOL
    - WHITE_WOOL
    - BLUE_WOOL
    - CYAN_WOOL
    - BROWN_WOOL
    - GRAY_WOOL
    - ORANGE_WOOL
    - PINK_WOOL
    - RED_WOOL
    - GREEN_WOOL
    - LIGHT_BLUE_WOOL
    - LIGHT_GRAY_WOOL
    - LIME_WOOL
    - MAGENTA_WOOL
    - PURPLE_WOOL
    - YELLOW_WOOL